swagger: '2.0'
info:
  version: "0.0.1"
  title: Bosh external CPI API
paths:
 /create_stemcell:
  post:
    summary: Create stemcell
    tags:
      - method
      - required
      - cli
      - stemcell
    externalDocs:
      description: Golang example
      url: https://github.com/cppforlife/bosh-warden-cpi/blob/master/action/create_stemcell.go
    externalDocs:
      description: light stemcell
      url: https://bosh.io/docs/stemcell.html
    description: |
      Creates a reusable VM image in the IaaS from the stemcell image. 
      It's used later for creating VMs. For example AWS CPI creates an AMI and returns AMI ID.
    parameters:
      - name: image_path
        in: query
        description: |
         path to the stemcell image on a local FS extracted from the stemcell tarball
        required: true
        type: string
      - name: cloud_properties  
        in: body
        description: |
         cloud properties hash extracted from the stemcell tarball
        required: true
        schema:
          type: array
          items:
            $ref: '#/definitions/PropertyItem'
    responses:
      default:
       description: Stemcell CID
       schema:
        $ref: '#/definitions/StemcellID'
definitions:
  PropertyItem:
    properties:
      name:
        type: string
        description: The property name.
      value:
        type: string
        description: The property value.
  StemcellID:
    type: string